# Adjust these parameters as needed
batch_size: 4
keep_original_fastq: false
# Base directory
base_dir: "/lustre/home/cebas/emlopez/rnaSeqAnalysis/test-run-snakemake"

# Metadata 
metadata: "/lustre/home/cebas/emlopez/rnaSeqAnalysis/test-run-snakemake/newMetadata20260701.tsv"

# References rRNA 
ref_18s: "/lustre/home/cebas/emlopez/rnaSeqAnalysis/prunusDulcis2/removeRNA/ref/silva-euk-18s-id95.fasta"
ref_28s: "/lustre/home/cebas/emlopez/rnaSeqAnalysis/prunusDulcis2/removeRNA/ref/silva-euk-28s-id98.fasta"

# Kallisto index
kallisto_index: "/lustre/home/cebas/emlopez/rnaSeqAnalysis/prunusDulcis2/kallisto/index/index_pdu_intergenics.idx"


