# Adjust these parameters as needed
batch_size: 4
keep_original_fastq: false
# Base directory
base_dir: ""
# Metadata 
metadata: ""

# References rRNA 
ref_18s: ""
ref_28s: ""

# Kallisto index
kallisto_index: ""


