rule sortmerna_paired:
    input:
        r1 = f"{FASTP_DIR}/{{run}}_1.fastp.fastq.gz",
        r2 = f"{FASTP_DIR}/{{run}}_2.fastp.fastq.gz"
    output:
        r1 = temp(f"{REMOVE_RNA_DIR}/{{run}}_nonrRNA_1.fq.gz"),
        r2 = temp(f"{REMOVE_RNA_DIR}/{{run}}_nonrRNA_2.fq.gz")
    params:
        ref_18s = REF_18S,
        ref_28s = REF_28S,
        workdir_18s = "/lustre/home/cebas/emlopez/rnaSeqAnalysis/snakeMake/index/18S_workdir",
        workdir_28s = "/lustre/home/cebas/emlopez/rnaSeqAnalysis/snakeMake/index/28S_workdir",
        workdir_run = f"{REMOVE_RNA_DIR}/temp_sortmerna/{{run}}",
        prefix = f"{REMOVE_RNA_DIR}/{{run}}_nonrRNA"
    wildcard_constraints:
        run = "[^_/]+"
    threads: 8
    resources:
        mem_mb = 65536
    shell:
        """
        set -e
        set +u
        module purge
        module load rama0.3
        module load Miniconda3/22.11.1-1
        source /dragofs/sw/foss/0.2/software/Miniconda3/4.9.2/etc/profile.d/conda.sh
        conda activate sortmerna
        set -u
        
        mkdir -p {params.workdir_run}
        mkdir -p {REMOVE_RNA_DIR}
        
        echo "==================================="
        echo "Processing  {wildcards.run} (PAIRED)"
        echo "==================================="
        date
        echo "Inputs:"
        ls -lh {input.r1} {input.r2}
        echo "Workdir: {params.workdir_run}"
        echo "Output prefix: {params.prefix}"
        echo "==================================="
        
        # Limpiar workdir previo
        if [ -d {params.workdir_run} ]; then
        echo "Limpiando workdir previo..."
        rm -rf {params.workdir_run}
        fi
        mkdir -p {params.workdir_run}
        

        echo "Running SortMeRNA ..."
        
        sortmerna --ref {params.ref_18s} \
                  --ref {params.ref_28s} \
                  --reads {input.r1} \
                  --reads {input.r2} \
                  --workdir {params.workdir_run} \
                  --fastx \
                  --other {params.prefix} \
                  --paired_out \
                  --out2 \
                  --threads {threads} \
                  -v
        

        echo "Files generated by SortMeRNA:"
        ls -lh {REMOVE_RNA_DIR}/ | grep {wildcards.run} || true
        
        # Rename format _1.fq.gz y _2.fq.gz


        if [ -f {params.prefix}_fwd.fq.gz ]; then
            echo "✓ Found paired output files."
            mv {params.prefix}_fwd.fq.gz {output.r1}
            mv {params.prefix}_rev.fq.gz {output.r2}
        else
            echo "ERROR: SortMeRNA paired output files were not found."
            echo "Expected:"
            echo "  - {params.prefix}_paired_fwd.fq.gz / {params.prefix}_paired_rev.fq.gz"
            echo "  - {params.prefix}_fwd.fq.gz / {params.prefix}_rev.fq.gz"
            echo ""
            echo "Files found:"
            ls -lh {REMOVE_RNA_DIR}/ | grep {wildcards.run} || true
            exit 1
        fi
        
        # Verified output files
        if [ ! -f {output.r1} ] || [ ! -f {output.r2} ]; then
            echo "ERROR: Failed to generate final output files."
            exit 1
        fi
        
        echo "Final output files:"
        ls -lh {output.r1} {output.r2}
        

        if [ ! -s {output.r1} ] || [ ! -s {output.r2} ]; then
            echo "ERROR: One or both files are empty. "
            exit 1
        fi
        
        echo "✓ Verification completed - Output files are valid:"
        du -h {output.r1} {output.r2}
        
        echo "Cleaning up temporary working directory..."
        rm -rf {params.workdir_run}
        
        echo "✓ Completed: {wildcards.run}"
        date
        echo "==================================="
        """
        



